Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Suri.Data;
using Suri.DTO;
using Suri.Models;

namespace Suri.Controllers
{


    public class ActividadesController : Controller
    {
        private readonly SuriDbContext _context;
        private readonly UserManager<MyUsers> userManager;
        public ActividadesController(SuriDbContext context, UserManager<MyUsers> userManager)
        {
            this.userManager = userManager;
            _context = context;
        }

        // GET: Actividades
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ActividadesAsignadas()
        {
            var suriDbContext = _context.Actividades
                .Include(a => a.Localidad)
                .Include(a => a.MyUser)
                .Include(a => a.Prioridad)
                .Where(x => x.Estado == false);

            return View(await suriDbContext.ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ActividadesRealizadas()
        {
            var suriDbContext = _context.Actividades
                .Include(a => a.Localidad)
                .Include(a => a.MyUser)
                .Include(a => a.Prioridad)
                .Where(x => x.Estado == true);
            return View(await suriDbContext.ToListAsync());
        }

        [Authorize(Roles = "Tecnico")]
        public async Task<IActionResult> ActividadesAsignadasTecnico()
        {
            string UserId = userManager.GetUserId(User);
            var suriDbContext = _context.Actividades
                .Include(a => a.Localidad)
                .Include(a => a.MyUser)
                .Include(a => a.Prioridad)
                .Where(x => x.Estado == false && x.MyUserId == UserId);
            return View(await suriDbContext.ToListAsync());
        }

        [Authorize(Roles = "Tecnico")]
        public async Task<IActionResult> ActividadesRealizadasTecnico()
        {
            string UserId = userManager.GetUserId(User);
            var suriDbContext = _context.Actividades
                .Include(a => a.Localidad)
                .Include(a => a.MyUser)
                .Include(a => a.Prioridad)
                .Where(x => x.Estado == true && x.MyUserId == UserId);

            return View(await suriDbContext.ToListAsync());
        }

        [Authorize(Roles = "Tecnico")]
        public async Task<IActionResult> RealizarActividad(int id)
        {
            string UserId = userManager.GetUserId(User);
            var actividad = await _context.Actividades
             .Include(a => a.Localidad)
             .Include(a => a.MyUser)
             .Include(a => a.Prioridad)
             .Where(x => x.Estado == false && x.MyUserId == UserId)
             .FirstOrDefaultAsync(m => m.Id == id);

            if (actividad == null)
            {
                return NotFound();
            }
            return View(actividad);
        }

        [HttpPost]
        [Authorize(Roles = "Tecnico")]
        public async Task<IActionResult> TerminarActividad(Actividades model)
        {

            string UserId = userManager.GetUserId(User);
            var actividad = await _context.Actividades.FindAsync(model.Id);

            if (actividad == null)
            {
                return NotFound();
            }
            if (actividad.MyUserId != UserId)
            {
                return NotFound();
            }


            actividad.Asistente = model.Asistente;
            actividad.FechaRealizacion = model.FechaRealizacion;
            actividad.Nota = model.Nota;
            actividad.accion = model.accion;
            actividad.Estado = true;
            if (model.Asistente == null || model.FechaRealizacion == null || model.accion == null)
            {
                return RedirectToAction("RealizarActividad", new { id = actividad.Id });

            }
            try
            {
                _context.Update(actividad);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ActividadesAsignadasTecnico));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ActividadesExists(actividad.Id))
                {
                    return View(actividad);

                }
                else
                {
                    throw;
                }
            }

        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actividades = await _context.Actividades
                .Include(a => a.Localidad)
                .Include(a => a.MyUser)
                .Include(a => a.Prioridad)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actividades == null)
            {
                return NotFound();
            }

            return View(actividades);
        }

        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Create()
        {
            ViewData["LocalidadId"] = new SelectList(_context.Set<Localidades>(), "Id", "Nombre");
            ViewData["MyUserId"] = new SelectList(await userManager.GetUsersInRoleAsync("Tecnico"), "Id", "UserName");
            ViewData["PrioridadId"] = new SelectList(_context.Prioridades.OrderByDescending(x => x.Id), "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Actividades actividades)
        {

            if (ModelState.IsValid)
            {
                _context.Add(actividades);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ActividadesAsignadas));
            }
            ViewData["LocalidadId"] = new SelectList(_context.Set<Localidades>(), "Id", "Nombre", actividades.LocalidadId);
            ViewData["MyUserId"] = new SelectList(_context.Users, "Id", "UserName", actividades.MyUserId);
            ViewData["PrioridadId"] = new SelectList(_context.Prioridades.OrderByDescending(x => x.Id), "Id", "Name");

            return View(actividades);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actividades = await _context.Actividades.FindAsync(id);
            if (actividades == null)
            {
                return NotFound();
            }
            ViewData["LocalidadId"] = new SelectList(_context.Set<Localidades>(), "Id", "Nombre", actividades.LocalidadId);
            ViewData["MyUserId"] = new SelectList(await userManager.GetUsersInRoleAsync("Tecnico"), "Id", "UserName", actividades.MyUserId);
            ViewData["PrioridadId"] = new SelectList(_context.Prioridades.OrderByDescending(x => x.Id), "Id", "Name");
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();

            return View(actividades);
        }

        [Authorize(Roles = "Admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string returnUrl, Actividades actividades)
        {
            if (id != actividades.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actividades);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActividadesExists(actividades.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect(returnUrl);
            }
            ViewData["LocalidadId"] = new SelectList(_context.Set<Localidades>(), "Id", "Nombre", actividades.LocalidadId);
            ViewData["UserId"] = new SelectList(await userManager.GetUsersInRoleAsync("Tecnico"), "Id", "UserName", actividades.MyUserId);
            ViewData["PrioridadId"] = new SelectList(_context.Prioridades.OrderByDescending(x => x.Id), "Id", "Name");

            return View(actividades);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actividades = await _context.Actividades
                .Include(a => a.Localidad)
                .Include(a => a.MyUser)
                .Include(a => a.Prioridad)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actividades == null)
            {
                return NotFound();
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();

            return View(actividades);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, string returnUrl)
        {
            var actividades = await _context.Actividades.FindAsync(id);
            _context.Actividades.Remove(actividades);
            await _context.SaveChangesAsync();
            return Redirect(returnUrl);
        }

        private bool ActividadesExists(int id)
        {
            return _context.Actividades.Any(e => e.Id == id);
        }
    }
}

Controllers/LocalidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Suri.Data;
using Suri.Models;

namespace Suri.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LocalidadesController : Controller
    {
        private readonly SuriDbContext _context;

        public LocalidadesController(SuriDbContext context)
        {
            _context = context;
        }

        // GET: Localidades
        public async Task<IActionResult> Index()
        {
            return View(await _context.Localidades.ToListAsync());
        }

        // GET: Localidades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localidades = await _context.Localidades
                .FirstOrDefaultAsync(m => m.Id == id);
            if (localidades == null)
            {
                return NotFound();
            }

            return View(localidades);
        }

        // GET: Localidades/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Localidades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Coordenadas,CeldaId")] Localidades localidades)
        {
            if (ModelState.IsValid)
            {
                _context.Add(localidades);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(localidades);
        }

        // GET: Localidades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localidades = await _context.Localidades.FindAsync(id);
            if (localidades == null)
            {
                return NotFound();
            }
            return View(localidades);
        }

        // POST: Localidades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Coordenadas,CeldaId")] Localidades localidades)
        {
            if (id != localidades.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(localidades);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocalidadesExists(localidades.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(localidades);
        }

        // GET: Localidades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var localidades = await _context.Localidades
                .FirstOrDefaultAsync(m => m.Id == id);
            if (localidades == null)
            {
                return NotFound();
            }

            return View(localidades);
        }

        // POST: Localidades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var localidades = await _context.Localidades.FindAsync(id);
            _context.Localidades.Remove(localidades);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocalidadesExists(int id)
        {
            return _context.Localidades.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<MyUsers> SignInManager;


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Index"]</title>
    <link href="https://fonts.googleapis.com/css2?family=Titillium" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />

    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>

        <nav class="navbar navbar-expand-lg bg-dark navbar-dark " data-toggle="collapse" and data-target="#thetarget" style="width: 100%;">

            <div class="navbar-brand logo-container">
                <img src="~/imgs/logo.png" alt="Alternate Text"/>
                <a class="text-white titulo" id="title">Suri Management System
                </a>
            </div>
            @if (SignInManager.IsSignedIn(User))
            {
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>



                <div class="collapse navbar-collapse " id="collapsibleNavbar">
                    <ul class="navbar-nav ml-auto float-lg-right mt-5 mb-5" id="menu-content">


                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#">Actividades</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="Actividades" asp-action="Create" class="dropdown-item">Asignar Nueva Actividad</a>
                                    <a asp-controller="Actividades" asp-action="ActividadesAsignadas" class="dropdown-item">Actividades Asignadas</a>
                                    <a asp-controller="Actividades" asp-action="ActividadesRealizadas" class="dropdown-item">Actividades Realizadas</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Localidades</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="Localidades" asp-action="Create" class="dropdown-item">Agregar Localidad</a>
                                    <a asp-controller="Localidades" asp-action="Index" class="dropdown-item">Lista de Localidades</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Administración</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="Empleados" asp-action="ListUsers" class="dropdown-item">Lista de Empleados</a>
                                    <a asp-controller="Empleados" asp-action="ListRoles" class="dropdown-item">Lista de Roles</a>
                                </div>
                            </li>


                        }
                        else if (SignInManager.IsSignedIn(User) && User.IsInRole("Tecnico"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Mis Actividades</a>
                                <div class="dropdown-menu">
                                    <a asp-controller="Actividades" asp-action="ActividadesAsignadasTecnico" class="dropdown-item">Actividades Asignadas</a>
                                    <a asp-controller="Actividades" asp-action="ActividadesRealizadasTecnico" class="dropdown-item">Actividades Realizadas</a>
                                </div>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <form asp-action="Logout" asp-controller="Account" method="post">
                                <button type="submit" asp-controller="Account" asp-action="Logout" class="p-2 nav-link btn btn-link ml-lg-5 bg-danger text-light btn-sm" style="width:auto">
                                    Cerrar Sesión @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    </ul>

                </div>

            }

        </nav>
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2020 - Suri Management
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>

    <script>
        // funcion del buscador
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>